// <auto-generated />
using MVCData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCData.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20221125130534_2")]
    partial class _2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVCData.ViewModels.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = "396d104b-43ea-4260-a197-1d4c9224b84d",
                            City = "ManCity",
                            Name = "Jake Paul",
                            Phone = "123289"
                        },
                        new
                        {
                            Id = "fbe56e9a-b6b5-4056-9263-b09d524727cd",
                            City = "Gothenburg",
                            Name = "Tony Stark",
                            Phone = "12345"
                        },
                        new
                        {
                            Id = "51665871-d702-41c0-b9a1-a25b9cb7b817",
                            City = "NewYork",
                            Name = "Captain America",
                            Phone = "3213213"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
