// <auto-generated />
using MVCData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCData.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVCData.ViewModels.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = "5bf7a66b-bcbf-4e44-bc63-de789f4186e1",
                            City = "ManCity",
                            Name = "Jake Paul",
                            Phone = "123289"
                        },
                        new
                        {
                            Id = "061e8a47-df0e-463b-8bc8-d82583ec1790",
                            City = "Gothenburg",
                            Name = "Tony Stark",
                            Phone = "12345"
                        },
                        new
                        {
                            Id = "46eb9338-7f43-4f25-a370-77d482bc2590",
                            City = "NewYork",
                            Name = "Captain America",
                            Phone = "3213213"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
