// <auto-generated />
using MVCData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCData.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LanguagePerson", b =>
                {
                    b.Property<int>("LanguagesID")
                        .HasColumnType("int");

                    b.Property<int>("PeopleID")
                        .HasColumnType("int");

                    b.HasKey("LanguagesID", "PeopleID");

                    b.HasIndex("PeopleID");

                    b.ToTable("LanguagePerson");

                    b.HasData(
                        new
                        {
                            LanguagesID = 1,
                            PeopleID = 1
                        },
                        new
                        {
                            LanguagesID = 1,
                            PeopleID = 2
                        },
                        new
                        {
                            LanguagesID = 2,
                            PeopleID = 1
                        },
                        new
                        {
                            LanguagesID = 2,
                            PeopleID = 2
                        },
                        new
                        {
                            LanguagesID = 2,
                            PeopleID = 3
                        },
                        new
                        {
                            LanguagesID = 3,
                            PeopleID = 2
                        },
                        new
                        {
                            LanguagesID = 3,
                            PeopleID = 3
                        },
                        new
                        {
                            LanguagesID = 3,
                            PeopleID = 4
                        });
                });

            modelBuilder.Entity("MVCData.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CountryID = 1,
                            Name = "Peking"
                        },
                        new
                        {
                            ID = 2,
                            CountryID = 2,
                            Name = "NewYork"
                        },
                        new
                        {
                            ID = 3,
                            CountryID = 3,
                            Name = "Gothenburg"
                        });
                });

            modelBuilder.Entity("MVCData.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "China"
                        },
                        new
                        {
                            ID = 2,
                            Name = "USA"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Sweden"
                        });
                });

            modelBuilder.Entity("MVCData.Models.Language", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Mandarin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "English"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Swedish"
                        });
                });

            modelBuilder.Entity("MVCData.ViewModels.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CityID = 1,
                            Name = "Tony",
                            Phone = "123289"
                        },
                        new
                        {
                            ID = 2,
                            CityID = 2,
                            Name = "Tony Stark",
                            Phone = "12345"
                        },
                        new
                        {
                            ID = 3,
                            CityID = 2,
                            Name = "Captain America",
                            Phone = "3213213"
                        },
                        new
                        {
                            ID = 4,
                            CityID = 3,
                            Name = "KrallLexicon",
                            Phone = "78998554"
                        });
                });

            modelBuilder.Entity("LanguagePerson", b =>
                {
                    b.HasOne("MVCData.Models.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVCData.ViewModels.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MVCData.Models.City", b =>
                {
                    b.HasOne("MVCData.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MVCData.ViewModels.Person", b =>
                {
                    b.HasOne("MVCData.Models.City", "City")
                        .WithMany("People")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MVCData.Models.City", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("MVCData.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
